name: state
description: Application state
version: 0.0.2
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  freezed_annotation: ^0.14.2

dev_dependencies:
  build_runner: ^2.0.5
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
